// src/components/dialogs/SettingsDialog.jsx
import { useEffect, useRef } from 'react'
import { useAppState } from '../../hooks/useAppState.js'
import { bump } from '../../hooks/useAppState.js'
import { state } from '../../Context/state.js'
import { vectorGui } from '../../GUI/vector.js'
import { initializeDragger } from '../../utils/drag.js'

export default function SettingsDialog() {
  useAppState()
  const ref = useRef(null)

  useEffect(() => {
    if (!ref.current) return
    initializeDragger(ref.current)
    return () => {
      delete ref.current?.dataset.dragInitialized
    }
  }, [])

  function handleClose() {
    state.ui.settingsOpen = false
    bump()
  }

  function handleTooltips(e) {
    state.ui.showTooltips = e.target.checked
    bump()
  }

  function handleGrid(e) {
    vectorGui.grid = e.target.checked
    vectorGui.render()
    bump()
  }

  function handleGridSpacingInput(e) {
    let val = parseInt(e.target.value)
    if (val < 1) val = 1
    else if (val > 64) val = 64
    vectorGui.gridSpacing = val
    vectorGui.render()
    bump()
  }

  function handleGridSpacingSpin(e) {
    const id = e.target.id || e.target.closest('[id]')?.id
    if (id === 'inc') {
      vectorGui.gridSpacing = Math.min(64, vectorGui.gridSpacing + 1)
    } else if (id === 'dec') {
      vectorGui.gridSpacing = Math.max(1, vectorGui.gridSpacing - 1)
    }
    vectorGui.render()
    bump()
  }

  function handleCursorPreview(e) {
    vectorGui.showCursorPreview = e.target.checked
  }

  return (
    <div
      ref={ref}
      className="settings-container dialog-box draggable v-drag h-drag free"
      style={{ display: state.ui.settingsOpen ? 'flex' : 'none' }}
    >
      <div id="settings-header" className="header dragger">
        <div className="drag-btn">
          <div className="grip"></div>
        </div>
        Settings
        <button
          type="button"
          className="close-btn"
          data-tooltip="Close"
          onClick={handleClose}
        ></button>
      </div>
      <div className="collapsible">
        <div className="settings-interface">
          <div className="settings-group">
            <div className="settings-section-header">Display</div>
            <div className="settings-options">
              <label
                htmlFor="tooltips-toggle"
                id="tooltips"
                className="toggle"
                data-tooltip="Toggle tooltips (T)"
              >
                <input
                  type="checkbox"
                  id="tooltips-toggle"
                  defaultChecked={true}
                  onChange={handleTooltips}
                />
                <span className="checkmark"></span>
                <span>Tooltips</span>
              </label>
              <label
                htmlFor="grid-toggle"
                id="grid"
                className="toggle"
                data-tooltip={'Toggle grid (G)\n\nDisplays at higher zoom levels only.'}
              >
                <input
                  type="checkbox"
                  id="grid-toggle"
                  checked={vectorGui.grid}
                  onChange={handleGrid}
                />
                <span className="checkmark"></span>
                <span>Grid</span>
              </label>
              <div className="grid-spacing-container">
                <label htmlFor="grid-spacing">
                  <span>Subgrid Spacing:&nbsp;</span>
                  <input
                    type="number"
                    id="grid-spacing"
                    min="1"
                    max="64"
                    value={vectorGui.gridSpacing}
                    onChange={handleGridSpacingInput}
                  />
                  <span className="grid-spacing-spin spin-btn" onPointerDown={handleGridSpacingSpin}>
                    <span id="inc" className="channel-btn">
                      <span className="spin-content">+</span>
                    </span>
                    <span id="dec" className="channel-btn">
                      <span className="spin-content">-</span>
                    </span>
                  </span>
                </label>
              </div>
              <label
                htmlFor="vector-outline-toggle"
                id="vector-outline"
                className="toggle"
                data-tooltip="Toggle vector selection outline"
              >
                <input type="checkbox" id="vector-outline-toggle" />
                <span className="checkmark"></span>
                <span>Vector Selection Outline</span>
              </label>
              <label
                htmlFor="cursor-preview-toggle"
                id="cursor-preview"
                className="toggle"
                data-tooltip="Show brush color preview under cursor instead of an outline"
              >
                <input
                  type="checkbox"
                  id="cursor-preview-toggle"
                  defaultChecked={true}
                  onChange={handleCursorPreview}
                />
                <span className="checkmark"></span>
                <span>Cursor Preview</span>
              </label>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// src/components/dialogs/SettingsDialog.svelte
<script>
  import { onMount } from 'svelte'
  import { getVersion, bump } from '../../hooks/appState.svelte.js'
  import { globalState } from '../../Context/state.js'
  import { vectorGui } from '../../GUI/vector.js'
  import { initializeDragger } from '../../utils/drag.js'

  let ref = $state(null)

  const isOpen = $derived(getVersion() >= 0 && globalState.ui.settingsOpen)
  const gridEnabled = $derived(getVersion() >= 0 && vectorGui.grid)
  const gridSpacing = $derived(getVersion() >= 0 ? vectorGui.gridSpacing : 1)

  onMount(() => {
    if (!ref) return
    initializeDragger(ref)
    return () => {
      delete ref?.dataset.dragInitialized
    }
  })

  function handleClose() {
    globalState.ui.settingsOpen = false
    bump()
  }

  function handleTooltips(e) {
    globalState.ui.showTooltips = e.target.checked
    bump()
  }

  function handleGrid(e) {
    vectorGui.grid = e.target.checked
    vectorGui.render()
    bump()
  }

  function handleGridSpacingInput(e) {
    let val = parseInt(e.target.value)
    if (val < 1) val = 1
    else if (val > 64) val = 64
    vectorGui.gridSpacing = val
    vectorGui.render()
    bump()
  }

  function handleGridSpacingSpin(e) {
    const id = e.target.id || e.target.closest('[id]')?.id
    if (id === 'inc') {
      vectorGui.gridSpacing = Math.min(64, vectorGui.gridSpacing + 1)
    } else if (id === 'dec') {
      vectorGui.gridSpacing = Math.max(1, vectorGui.gridSpacing - 1)
    }
    vectorGui.render()
    bump()
  }

  function handleCursorPreview(e) {
    vectorGui.showCursorPreview = e.target.checked
  }
</script>

<div
  bind:this={ref}
  class="settings-container dialog-box draggable v-drag h-drag free"
  style="display: {isOpen ? 'flex' : 'none'}"
>
  <div id="settings-header" class="header dragger">
    <div class="drag-btn">
      <div class="grip"></div>
    </div>
    Settings
    <button type="button" class="close-btn" data-tooltip="Close" onclick={handleClose}></button>
  </div>
  <div class="collapsible">
    <div class="settings-interface">
      <div class="settings-group">
        <div class="settings-section-header">Display</div>
        <div class="settings-options">
          <label
            for="tooltips-toggle"
            id="tooltips"
            class="toggle"
            data-tooltip="Toggle tooltips (T)"
          >
            <input
              type="checkbox"
              id="tooltips-toggle"
              checked={true}
              onchange={handleTooltips}
            />
            <span class="checkmark"></span>
            <span>Tooltips</span>
          </label>
          <label
            for="grid-toggle"
            id="grid"
            class="toggle"
            data-tooltip="Toggle grid (G)\n\nDisplays at higher zoom levels only."
          >
            <input
              type="checkbox"
              id="grid-toggle"
              checked={gridEnabled}
              onchange={handleGrid}
            />
            <span class="checkmark"></span>
            <span>Grid</span>
          </label>
          <div class="grid-spacing-container">
            <label for="grid-spacing">
              <span>Subgrid Spacing:&nbsp;</span>
              <input
                type="number"
                id="grid-spacing"
                min="1"
                max="64"
                value={gridSpacing}
                oninput={handleGridSpacingInput}
              />
              <span
                class="grid-spacing-spin spin-btn"
                onpointerdown={handleGridSpacingSpin}
              >
                <span id="inc" class="channel-btn">
                  <span class="spin-content">+</span>
                </span>
                <span id="dec" class="channel-btn">
                  <span class="spin-content">-</span>
                </span>
              </span>
            </label>
          </div>
          <label
            for="vector-outline-toggle"
            id="vector-outline"
            class="toggle"
            data-tooltip="Toggle vector selection outline"
          >
            <input type="checkbox" id="vector-outline-toggle" />
            <span class="checkmark"></span>
            <span>Vector Selection Outline</span>
          </label>
          <label
            for="cursor-preview-toggle"
            id="cursor-preview"
            class="toggle"
            data-tooltip="Show brush color preview under cursor instead of an outline"
          >
            <input
              type="checkbox"
              id="cursor-preview-toggle"
              checked={true}
              onchange={handleCursorPreview}
            />
            <span class="checkmark"></span>
            <span>Cursor Preview</span>
          </label>
        </div>
      </div>
    </div>
  </div>
</div>
